const router = require('express').Router()

const announcement = require('./announcement')
const news = require('./news')
const bookingRoom = require('./bookingRoom')
const event = require('./event')
const user = require('./user')
const contact = require('./contact')
const company = require('./company')
const department = require('./department')
const notification = require('./notification')
const kritikSaran = require('./kritikSaran')
const kpim = require('./kpim')
const tal = require('./tal')
const rewardKPIM = require('./rewardKPIM')
const position = require('./position')
const pic = require('./pic')
const address = require('./address')
const structure = require('./structure')
const building = require('./building')
const dinas = require('./dinas')
const designation = require('./designation')
const security = require('./security')
const helpdesk = require('./helpdesk')

router.get('/', (req, res) => {
    res.send('Welcome to server polaku-react')
})
router.use('/announcement', announcement)
router.use('/news', news)
router.use('/bookingRoom', bookingRoom)
router.use('/events', event)
router.use('/users', user)
router.use('/contactUs', contact)
router.use('/company', company)
router.use('/department', department)
router.use('/notification', notification)
router.use('/kritikSaran', kritikSaran)
router.use('/kpim', kpim)
router.use('/tal', tal)
router.use('/rewardKPIM', rewardKPIM)
router.use('/position', position)
router.use('/pic', pic)
router.use('/address', address)
router.use('/structure', structure)
router.use('/building', building)
router.use('/dinas', dinas)
router.use('/designation', designation)
router.use('/security', security)
router.use('/helpdesk', helpdesk)

module.exports = router
